FROM python:3.10-slim

WORKDIR /app

# Incluye la raíz del contenedor y las subcarpetas para resolver todas las importaciones
ENV PYTHONPATH=/app:/app/mlops_fraudulent_transactions

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "mlops_fraudulent_transactions.api.api:app", "--host", "0.0.0.0", "--port", "8000"]