name: mlops_fraudulent_transactions
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ruff
  - pytest
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - tensorflow
  - dvc
  - pip:
    - python-dotenv
    - mkdocs
    - -e .
    - dvc-gdrive