[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mlops_fraudulent_transactions"
version = "0.0.1"
description = "MLOPS setup for a fraudulent transaction dataset"
authors = [
  { name = "MLOPS Group 1" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["mlops_fraudulent_transactions"]
include = ["pyproject.toml", "mlops_fraudulent_transactions/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["mlops_fraudulent_transactions"]
force-sort-within-sections = true

